### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by adhoc2github** [openai/cleverhans#115]
I run the test_mnist_accuracy.py, meet the following error:
Using TensorFlow backend.
X_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
/anaconda/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/utils.py:143: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (8, 8), padding="same", strides=(2, 2))`
  border_mode="same"
/anaconda/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/utils.py:147: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (6, 6), padding="valid", strides=(2, 2))`
  border_mode="valid"),
/anaconda/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/utils.py:149: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (5, 5), strides=(1, 1))`
  Convolution2D(nb_filters * 2, 5, 5, subsample=(1, 1)),
Defined TensorFlow model graph.
Epoch 0
        Epoch took 8.60225486755 seconds
Epoch 1
        Epoch took 8.84567499161 seconds
Completed model training.
Traceback (most recent call last):

  File "<ipython-input-1-4bcd96e1bffd>", line 1, in <module>
    runfile('/Users/adhockuang/myworkspace/cleverhans-master/tests_tf/test_mnist_accuracy.py', wdir='/Users/adhockuang/myworkspace/cleverhans-master/tests_tf')

  File "/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/Users/adhockuang/myworkspace/cleverhans-master/tests_tf/test_mnist_accuracy.py", line 84, in <module>
    app.run()

  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))

  File "/Users/adhockuang/myworkspace/cleverhans-master/tests_tf/test_mnist_accuracy.py", line 76, in main
    args=eval_params)

  File "/anaconda/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/utils_tf.py", line 206, in model_eval
    keras.backend.learning_phase(): 0})

ValueError: operands could not be broadcast together with shapes (128,) (80,) (128,)

**Comment by kudkudak** [comment]
Code ATM requires keras<2.0.0, can you try rerunning with keras==1.2.2?

**Comment by adhoc2github** [comment]
thanks, I will try.

**Comment by npapernot** [comment]
@adhoc2github Can you let us know if it worked?

**Comment by npapernot** [comment]
Closing this given that we did not receive any response from @adhoc2github 

Feel free to reopen if the bug is still reproducible
