### ISSUE TITLE
jsma causes InternalError

### ISSUE THREAD

**Issue by kirk86** [openai/cleverhans#132]
Hi everyone and thanks for this work. I was wondering if you could give me some hint on a problem that I'm facing. Recently I've been trying to run the `mnist_tutorial_jsma.py`. So I've took that example and replaced all the  `tf.flags` with `argparse` since IMHO I find it more intuitive and less boilerplate than the `tf.flags`. Below is a simple example of the code that I'm trying to run.

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import keras.backend as K
import numpy as np
import argparse
from six.moves import xrange
import tensorflow as tf

from cleverhans.attacks import SaliencyMapMethod
from cleverhans.utils import other_classes, cnn_model, pair_visual, grid_visual
from cleverhans.utils_mnist import data_mnist
from cleverhans.utils_tf import model_train, model_eval, model_argmax

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Arguments for "
                                     "adversarial samples.")
    parser.add_argument("-b", "--batch_size", type=int, default=128,
                        help="Batch size for training "
                        "and testing the model")
    parser.add_argument("-e", "--epochs", type=int, default=15,
                        help="Nb of epochs for training")
    parser.add_argument("-lr", "--learning_rate", type=float, default=0.1,
                        help="Learning rate during training.")
    parser.add_argument("-c", "--nb_classes", type=int, default=10,
                        help="Choose the number of classes in your"
                        " dataset")
    parser.add_argument("-gv", "--grid_visual", type=bool, default=False,
                        help="Plot normal and distorted image from "
                             "particular target classs")
    parser.add_argument("-nas", "--nb_attack_samples", type=int, default=10,
                        help="Nb ot test set examples to attack")
    args = parser.parse_args()

    K.set_learning_phase(0)

    # Set TF random seed to improve reproducibility
    tf.set_random_seed(2017)

    # Create TF session and set as Keras backend session
    sess = tf.Session()
    K.set_session(sess)
    print("Created TensorFlow session and set Keras backend.")

    # Get MNIST test data
    X_train, Y_train, X_test, Y_test = data_mnist()
    img_rows, img_cols, nb_channels = X_test[0].shape
    print("Loaded MNIST test data.")

    # Define input TF placeholder
    x = tf.placeholder(tf.float32, shape=(None, 28, 28, 1))
    y = tf.placeholder(tf.float32, shape=(None, 10))

    # Define TF model graph
    model = cnn_model()
    preds = model(x)
    print("Defined TensorFlow model graph.")

    ###################################################################
    # Training the model using TensorFlow
    ###################################################################
    train_params = {
        'nb_epochs': args.epochs,
        'batch_size': args.batch_size,
        'learning_rate': args.learning_rate
    }
    model_train(sess, x, y, preds, X_train, Y_train,
                args=train_params)

    # Evaluate the accuracy of the MNIST model on legitimate test examples
    eval_params = {'batch_size': args.batch_size}
    accuracy = model_eval(sess, x, y, preds, X_test, Y_test,
                          args=eval_params)
    assert X_test.shape[0] == 10000, X_test.shape
    print('Test accuracy on legitimate test examples: {0}'.format(accuracy))

    ###########################################################################
    # Craft adversarial examples using the Jacobian-based saliency map approach
    ###########################################################################
    print('Crafting ' + str(args.nb_attack_samples) + ' * ' +
          str(args.nb_classes-1) + ' adversarial examples')

    # Keep track of success (adversarial example classified in target)
    results = np.zeros((args.nb_classes, args.nb_attack_samples), dtype='i')

    # Rate of perturbed features for each test set example and target class
    perturbations = np.zeros((args.nb_classes, args.nb_attack_samples),
                             dtype='f')

    # Initialize our array for grid visualization
    grid_shape = (args.nb_classes,
                  args.nb_classes,
                  img_rows,
                  img_cols,
                  nb_channels)
    grid_viz_data = np.zeros(grid_shape, dtype='f')

    # Define the SaliencyMapMethod attack object
    jsma = SaliencyMapMethod(model, back='tf', sess=sess)
    current_class = int(np.argmax(Y_test[0]))
    target_classes = other_classes(args.nb_classes, current_class)
    one_hot_target = np.zeros((1, args.nb_classes), dtype=np.float32)
    one_hot_target[0, target_classes[0]] = 1
    jsma_params = {'theta': 1., 'gamma': 0.1,
                   'nb_classes': args.nb_classes, 'clip_min': 0.,
                   'clip_max': 1., 'targets': y,
                   'y_val': one_hot_target}

    adv_x = jsma.generate_np(X_test[0:(0+1)],
                             **jsma_params)

    # Close TF session
    sess.close()
```

Every time that I try to run the above example I end up getting the following error.
```
Created TensorFlow session and set Keras backend.
X_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Loaded MNIST test data.
Defined TensorFlow model graph.
Epoch 0
	Epoch took 165.463960886 seconds
Epoch 1
	Epoch took 178.119558096 seconds
Completed model training.
Test accuracy on legitimate test examples: 0.9418
Crafting 10 * 9 adversarial examples
--------------------------------------
Attacking input 1/10
Generating adv. example for target class 0
Traceback (most recent call last):
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks.py", line 340, in jsma_wrap
    targets=targets)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks_tf.py", line 327, in jsma_batch
    theta, gamma, clip_min, clip_max)


  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks_tf.py", line 264, in jsma
    nb_features, FLAGS.nb_classes)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 50, in __getattr__
    raise AttributeError(name)
AttributeError: nb_classes
2017-05-09 17:29:23.088024: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_0: see error log.
Traceback (most recent call last):
  File "test_jsma.py", line 131, in <module>
    **jsma_params)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks.py", line 384, in generate_np
    return self.sess.run(self._x_adv, feed_dict=feed_dict)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_0: see error log.
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_2_0, _recv_Placeholder_1_0)]]

Caused by op u'PyFunc', defined at:
  File "test_jsma.py", line 131, in <module>
    **jsma_params)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks.py", line 368, in generate_np
    self._x_adv = self.generate(self._x, **kwargs)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks.py", line 343, in generate
    wrap = tf.py_func(jsma_wrap, [x, self.targets], tf.float32)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_0: see error log.
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_2_0, _recv_Placeholder_1_0)]]
```

Any comments or hints are much appreciated!

**Comment by RiaanZoetmulder** [comment]
I have this exact error too

**Comment by RiaanZoetmulder** [comment]
Hello,

I have basically copy pasted the necessary functions in an Ipython notebook, and am trying to replicate the jsma example, but without using keras and doing it fully in tensorflow.

So i am still using the original functions, just instead of keras giving me predictions a neural network in tensorflow gives me predictions.

Now I have made the exact same alteration to the exact same function you have made (def jsma). This error keeps occurring however.

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.pyc in __call__(self, token, args)
     81     if func is None:
     82       raise ValueError("callback %s is not found" % token)
---> 83     ret = func(*args)
     84     # Ensures that we return either a single numpy array or a list of numpy
     85     # arrays.

<ipython-input-5-044e80281f55> in jsma_wrap(x_val, targets)
     19                                       self.theta, self.gamma, self.clip_min,
     20                                       self.clip_max, self.nb_classes,
---> 21                                       targets=targets)
     22 
     23             wrap = tf.py_func(jsma_wrap, [x, self.targets], tf.float32)

<ipython-input-4-dc75245c381b> in jsma_batch(sess, x, pred, grads, X, theta, gamma, clip_min, clip_max, nb_classes, targets)
    240 
    241         X_adv[ind], _, _ = jsma(sess, x, pred, grads, val, np.argmax(target),
--> 242                                 theta, gamma, clip_min, clip_max)
    243 
    244     return np.asarray(X_adv, dtype=np.float32)

<ipython-input-4-dc75245c381b> in jsma(sess, x, predictions, grads, sample, target, theta, gamma, clip_min, clip_max)
    167     iteration = 0
    168     adv_x_original_shape = np.reshape(adv_x, original_shape)
--> 169     current = model_argmax(sess, x, predictions, adv_x_original_shape)
    170 
    171     # Repeat this main loop until we have achieved misclassification

<ipython-input-4-dc75245c381b> in model_argmax(sess, x, predictions, samples)
    256 
    257 
--> 258     probabilities = sess.run(predictions, feed_dict)
    259 
    260     if samples.shape[0] == 1:

/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    715     try:
    716       result = self._run(None, fetches, feed_dict, options_ptr,
--> 717                          run_metadata_ptr)
    718       if run_metadata:
    719         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    913     if final_fetches or final_targets:
    914       results = self._do_run(handle, final_targets, final_fetches,
--> 915                              feed_dict_string, options, run_metadata)
    916     else:
    917       results = []

/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
    963     if handle is None:
    964       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
--> 965                            target_list, options, run_metadata)
    966     else:
    967       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
    983         except KeyError:
    984           pass
--> 985       raise type(e)(node_def, op, message)
    986 
    987   def _extend_graph(self):

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'Placeholder', defined at:
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-b1ffcfb60990>", line 145, in <module>
    JSMA(cifar10)
  File "<ipython-input-6-b1ffcfb60990>", line 25, in JSMA
    x = tf.placeholder(tf.float32, shape = [None, 32,32,3])
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1332, in placeholder
    name=name)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1748, in _placeholder
    name=name)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]


---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-6-b1ffcfb60990> in <module>()
    143 
    144 
--> 145 JSMA(cifar10)
    146 
    147 

<ipython-input-6-b1ffcfb60990> in JSMA(cifar10, classes, reg)
     86                            'y_val': one_hot_target}
     87             adv_x = jsma.generate_np(X_test[sample_ind:(sample_ind+1)],
---> 88                                      **jsma_params)
     89 
     90 

<ipython-input-5-044e80281f55> in generate_np(self, x_val, **kwargs)
     56             feed_dict = {self._x: x_val.astype('float32'), self.targets: kwargs['y_val'].astype('float32')}
     57             print 'here'
---> 58         return self.sess.run(self._x_adv, feed_dict=feed_dict)
     59 
     60 

/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    715     try:
    716       result = self._run(None, fetches, feed_dict, options_ptr,
--> 717                          run_metadata_ptr)
    718       if run_metadata:
    719         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    913     if final_fetches or final_targets:
    914       results = self._do_run(handle, final_targets, final_fetches,
--> 915                              feed_dict_string, options, run_metadata)
    916     else:
    917       results = []

/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
    963     if handle is None:
    964       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
--> 965                            target_list, options, run_metadata)
    966     else:
    967       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
    983         except KeyError:
    984           pass
--> 985       raise type(e)(node_def, op, message)
    986 
    987   def _extend_graph(self):

InternalError: Failed to run py callback pyfunc_0: see error log.
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_2_0, _recv_Placeholder_1_0)]]

Caused by op u'PyFunc', defined at:
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-b1ffcfb60990>", line 145, in <module>
    JSMA(cifar10)
  File "<ipython-input-6-b1ffcfb60990>", line 88, in JSMA
    **jsma_params)
  File "<ipython-input-5-044e80281f55>", line 40, in generate_np
    self._x_adv = self.generate(self._x, **kwargs)
  File "<ipython-input-5-044e80281f55>", line 23, in generate
    wrap = tf.py_func(jsma_wrap, [x, self.targets], tf.float32)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 174, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 39, in _py_func
    name=name)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/riaan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_0: see error log.
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_2_0, _recv_Placeholder_1_0)]]

@npapernot 

Do you have any idea what could be causing this? If you wish I can send you what I have done.
