### ISSUE TITLE
Gamma hyperparameter causes crash.

### ISSUE THREAD

**Issue by RiaanZoetmulder** [openai/cleverhans#143]
Hello, 

I have been playing around with the Jacobian Salience Map method of creating adversarial examples. If I understand it correctly, this hyperparameter indicates what percentage is allowed to change maximally.
However, if I train a network and set gamma too high, it causes some sort of cryptic crash.

I'll keep looking at it but as of yet I haven't figured it out.

Here is the error log:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.pyc in __call__(self, token, args)
     80     if func is None:
     81       raise ValueError("callback %s is not found" % token)
---> 82     ret = func(*args)
     83     # Ensures that we return either a single numpy array or a list of numpy
     84     # arrays.

<ipython-input-4-baac389e7bba> in jsma_wrap(x_val, targets)
     40                                   self.theta, self.gamma, self.clip_min,
     41                                   self.clip_max, self.nb_classes,
---> 42                                   targets=targets)
     43 
     44             # Attack is targeted, target placeholder will need to be fed

/home/riaan/src/cleverhans/cleverhans/attacks_tf.pyc in jsma_batch(sess, x, pred, grads, X, theta, gamma, clip_min, clip_max, nb_classes, targets)
    328 
    329         X_adv[ind], _, _ = jsma(sess, x, pred, grads, val, np.argmax(target),
--> 330                                 theta, gamma, clip_min, clip_max)
    331 
    332     return np.asarray(X_adv, dtype=np.float32)

/home/riaan/src/cleverhans/cleverhans/attacks_tf.pyc in jsma(sess, x, predictions, grads, sample, target, theta, gamma, clip_min, clip_max)
    270         # and return the two best candidate features for perturbation
    271         i, j, search_domain = saliency_map(
--> 272             grads_target, grads_others, search_domain, increase)
    273 
    274         # Apply the perturbation to the two input features selected previously

/home/riaan/src/cleverhans/cleverhans/attacks_tf.pyc in saliency_map(grads_target, grads_other, search_domain, increase)
    150     # Remove used pixels from our search domain
    151     search_domain.remove(p1)
--> 152     search_domain.remove(p2)
    153 
    154     return p1, p2, search_domain

KeyError: 0

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-8-4c82c8f256ec> in <module>()
----> 1 z_list, z_test = module.JSMA_generate()

<ipython-input-6-17f5c0f546a4> in JSMA_generate(self)
    581                 adv_z = jsma.generate_np(z_test[sample_ind:(sample_ind+1)],
    582                                          self.decoder,self.use_rec,
--> 583                                          **jsma_params)
    584 
    585                 if zs ==None:

<ipython-input-4-baac389e7bba> in generate_np(self, z_val, decoder, use_rec, **kwargs)
     87             feed_dict = {self._z: z_val, self.targets: kwargs['y_val'], use_rec:True,
     88                          self.jsma:True }
---> 89         return self.sess.run(self._z_adv, feed_dict=feed_dict)
     90 
     91     def parse_params(self, theta=1., gamma=np.inf, nb_classes=10, clip_min=0.,

/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    776     try:
    777       result = self._run(None, fetches, feed_dict, options_ptr,
--> 778                          run_metadata_ptr)
    779       if run_metadata:
    780         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    980     if final_fetches or final_targets:
    981       results = self._do_run(handle, final_targets, final_fetches,
--> 982                              feed_dict_string, options, run_metadata)
    983     else:
    984       results = []

/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1030     if handle is None:
   1031       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1032                            target_list, options, run_metadata)
   1033     else:
   1034       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1050         except KeyError:
   1051           pass
-> 1052       raise type(e)(node_def, op, message)
   1053 
   1054   def _extend_graph(self):

InternalError: Failed to run py callback pyfunc_24: see error log.
	 [[Node: PyFunc_24 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_24", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_24_0, _recv_labels_0)]]

Caused by op u'PyFunc_24', defined at:
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-4c82c8f256ec>", line 1, in <module>
    z_list, z_test = module.JSMA_generate()
  File "<ipython-input-6-17f5c0f546a4>", line 583, in JSMA_generate
    **jsma_params)
  File "<ipython-input-4-baac389e7bba>", line 72, in generate_np
    self._z_adv = self.generate(self._z, **kwargs)
  File "<ipython-input-4-baac389e7bba>", line 45, in generate
    wrap = tf.py_func(jsma_wrap, [x, self.targets], tf.float32)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/riaan/anaconda2/envs/tensorflow1.0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_24: see error log.
	 [[Node: PyFunc_24 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_24", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_24_0, _recv_labels_0)]]

I am running this on tensorflow 1 in anaconda. 

kind regards,

Riaan Zoetmulder

@npapernot

**Comment by RiaanZoetmulder** [comment]
This may have already been solved by: https://github.com/openai/cleverhans/pull/122 actually.

Can be closed.

**Comment by npapernot** [comment]
Yes, the key error should be adressed by #122, thanks for confirming!
