### ISSUE TITLE
theano tutorial is broken

### ISSUE THREAD

**Issue by goodfeli** [openai/cleverhans#60]
`python tutorials/mnist_tutorial_th.py 
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
Loaded MNIST test data.
Traceback (most recent call last):
  File "tutorials/mnist_tutorial_th.py", line 98, in <module>
    main()
  File "tutorials/mnist_tutorial_th.py", line 48, in main
    predictions = model(x)
  File "/home/ian/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 574, in __call__
    outputs = to_list(self.call(x, mask))
  File "/home/ian/.local/lib/python3.5/site-packages/keras/models.py", line 381, in call
    return self.model.call(x, mask)
  File "/home/ian/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 2240, in call
    output_tensors, output_masks, output_shapes = self.run_internal_graph(inputs, masks)
  File "/home/ian/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 2383, in run_internal_graph
    computed_mask))
  File "/home/ian/.local/lib/python3.5/site-packages/keras/layers/core.py", line 90, in call
    x = K.in_train_phase(K.dropout(x, self.p, noise_shape), x)
  File "/home/ian/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2051, in dropout
    return tf.nn.dropout(x * 1., retain_prob, noise_shape, seed=seed)
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1743, in dropout
    x = ops.convert_to_tensor(x, name="x")
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got Elemwise{mul,no_inplace}.0`

**Comment by goodfeli** [comment]
@mahnerak can you fix this?

**Comment by mahnerak** [comment]
> Using TensorFlow backend.

You need to somehow specify which backend to use for Keras. You have to either edit your keras.json config file or run every time like this
`KERAS_BACKEND=theano python mnist_tutorial_th.py`

**Comment by goodfeli** [comment]
Because the tutorial works only with the theano backend, you should use an if starement and change the backend if necessary, just as the tensorflow tutorial does

**Comment by goodfeli** [comment]
Or at least give a useful error message

**Comment by mahnerak** [comment]
Actually, the TensorFlow version of tutorial changes only image dimension ordering, not a backend for Keras.
If you run `mnist_tutorial_tf.py` with Keras configured theano as default backend, you'll get
> Using Theano backend.
Using gpu device 0: GeForce GTX 980 (CNMeM is disabled, cuDNN 5005)
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.7.5 locally
INFO: '~/.keras/keras.json' sets 'image_dim_ordering' to 'th', temporarily setting to 'tf'
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
F tensorflow/stream_executor/cuda/cuda_driver.cc:334] current context was not created by the StreamExecutor cuda_driver API: 0x254a160; a CUDA runtime call was likely performed without using a StreamExecutor context
[1]    30067 abort (core dumped)  KERAS_BACKEND=theano python mnist_tutorial_tf.py

**Comment by mahnerak** [comment]
Which one do you prefer? To assert that backend is correct, or change it manually.
If we decide to change backend during runtime, we have to do something like this before importing Keras
`os.environ['KERAS_BACKEND']='tensorflow'`

**Comment by goodfeli** [comment]
OK, I see the issue. I'll take care of this, actually.
