### ISSUE TITLE
JSMA tutorial crashes while trying to save

### ISSUE THREAD

**Issue by goodfeli** [openai/cleverhans#62]
Traceback (most recent call last):
  File "tutorials/mnist_tutorial_jsma.py", line 140, in <module>
    app.run()
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tutorials/mnist_tutorial_jsma.py", line 83, in main
    saver.save(sess, save_path)
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1329, in save
    self.last_checkpoints, latest_filename)
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 745, in update_checkpoint_state
    text_format.MessageToString(ckpt))
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 351, in atomic_write_string_to_file
    rename(temp_pathname, filename, overwrite=True)
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 333, in rename
    compat.as_bytes(oldname), compat.as_bytes(newname), overwrite, status)
  File "/opt/anaconda/4.2.0/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /tmp/checkpoint.tmp87146825c2f043aa9c3fd9f92e3efa98

**Comment by mahnerak** [comment]
What are the permissions for your /tmp directory?

**Comment by goodfeli** [comment]
This seems fixed now. Maybe permissions were temporarily set wrong on our machine.
